### ISSUE TITLE
Swagger enums are not imported as ApiDoc enum definitions

### ISSUE THREAD

**Issue by fabiocognigni** [mbryzek/apidoc#517]
### Steps to reproduce:
* create an API swagger definition with an enum (String) property;
E.g.
```
definitions:
...
Country:
    type: object
    properties:
      code:
        type: string
        enum:
            - US
            - CA
....
```
* import it into Apidoc (selecting `swagger.json 2.0` Type).

### Expected behaviour:
An Apidoc enum has been defined.

### Actual behaviour:
No Apidoc enums have been defined.

### Example:
* https://app.swaggerhub.com/api/fabiocognigni/geo-location-api/1.0.0
* http://www.apidoc.me/gilt/geo-location-api/0.0.1
